# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 183953d0735638c0642fc00389aef20271181e892d44741149b65623fd3e98101acf8094bba9dff6038d8ad0a562a9cccd40aae0cd925a44a51eef1732adffb9

test:
  secret_key_base: e68ce50546d1a5474155006e32b1a125e3d9072989868a4e058c1c51b3e646293f67c8f9aba9ff3582520cac8cadbe1a6057b42f8dedf01772d4850460d25dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
